### ISSUE TITLE
Configuration to disable enchantment completely

### ISSUE THREAD

**Issue by frenchiveruti** [RakambdaOrg/FallingTree#295] opened 2022-01-17 00:36 UTC
### Describe the feature

Title. 

I find myself using the mod just to not be climbing to trees and getting logs inside branches.  

I don't use the instant chopping.

Therefore, I'd like to **disable the enchantment** completely, as I found out that it can enchant **shovels** for some reason. 
![imagen](https://user-images.githubusercontent.com/1095997/149684634-5ab7216c-f228-402a-a26a-e5ddbbb007b4.png)

Thanks,

**Comment by Rakambda** [comment] 2022-01-17 04:23
Duplicate of #284

**Closed as not planned** 2022-01-17 04:24 UTC
Labels: status: duplicate, type: 🧱 enhancement
