### ISSUE TITLE
Game wont start, claiming that it only support a mod that is already installed

### ISSUE THREAD

**Issue by SneakyDevil** [RakambdaOrg/FallingTree#104] opened 2021-05-04 18:04 UTC
![image](https://user-images.githubusercontent.com/11374726/117048959-9279b180-ace1-11eb-97eb-00674839272f.png)

**Comment by Rakambda** [comment] 2021-05-05 05:44
Duplicate of #98

**Closed as not planned** 2021-05-05 05:44 UTC
Labels: type: 🐛 bug, status: duplicate, modloader: Forge
