### ISSUE TITLE
Randomly crash immediately upon clicking (cutting) tree block

### ISSUE THREAD

**Issue by dull4h4n** [RakambdaOrg/FallingTree#188] opened 2021-08-09 23:28 UTC
### Describe the bug

This does not happen very often, but it does from time to time. 
My only non-default settings are:
Damage 1
Speed multi: 1.0

It seems to happen almost every time I create a new world cutting with of the first few trees with an axe. Then it happens very infrequently.

Most common bug is breaking the tree block and then when it should break the entire tree, it plays the tree break sound and block starts over.

### Minecraft version

1.17

### Fabric API version

0.36.0

### Mod version

2.12.1

### Relevant log output

```shell
---- Minecraft Crash Report ----
// Why did you do that?

Time: 8/9/21, 5:38 PM
Description: Unexpected error

java.util.ConcurrentModificationException
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.13)
	at java.util.HashMap.compute(HashMap.java:1321)
	at net.minecraft.block.AbstractBlock.handler$zli000$calcBlockBreakingDelta(AbstractBlock:532)
	at net.minecraft.block.AbstractBlock.calcBlockBreakingDelta(AbstractBlock:378)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.calcBlockBreakingDelta(AbstractBlock:794)
	at net.minecraft.client.network.ClientPlayerInteractionManager.attackBlock(ClientPlayerInteractionManager:174)
	at net.minecraft.client.network.ClientPlayerInteractionManager.updateBlockBreakingProgress(ClientPlayerInteractionManager:257)
	at net.minecraft.client.MinecraftClient.handleBlockBreaking(MinecraftClient:1555)
	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient:1913)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1730)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1083)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:730)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.HashMap.compute(HashMap.java:1321)
	at net.minecraft.class_4970.handler$zli000$calcBlockBreakingDelta(class_4970.java:532)
	at net.minecraft.class_4970.method_9594(class_4970.java:378)
	at net.minecraft.class_4970$class_4971.method_26165(class_4970.java:794)
	at net.minecraft.class_636.method_2910(class_636.java:174)
	at net.minecraft.class_636.method_2902(class_636.java:257)

-- Affected level --
Details:
	All players: 1 total; [class_746['Dulhan'/4, l='ClientLevel', x=591.62, y=65.00, z=2591.11]]
	Chunk stats: 1024, 483
	Level dimension: minecraft:overworld
	Level spawn location: World: (96,64,-176), Section: (at 0,0,0 in 6,4,-11; chunk contains blocks 96,-64,-176 to 111,319,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 608357 game time, 917038 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28)
	at net.minecraft.class_310.modify$zlb000$onCrash(class_310.java:4099)
	at net.minecraft.class_310.method_1514(class_310.java:754)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Faithful 1.17.zip, Conquest_entities_1.16.zip

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2079130368 bytes (1982 MiB) / 6517948416 bytes (6216 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1070 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b82
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.40
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.40
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 32706.57
	Virtual memory used (MB): 26141.30
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		antiqueatlas: Antique Atlas 6.0.0-fabric-mc1.17.1
		appleskin: AppleSkin mc1.17-2.1.2
		architectury: Architectury 2.3.24
		bettermineshafts: YUNG's Better Mineshafts 1.17-1.0.1
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		betterthirdperson: Better Third Person 1.5.0
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		caves-and-cliffs-add-on-for-william-wythers-overhauled-overworld: Caves and Cliffs add-on for William Wythers Overhauled Overworld 1.2
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 0.0.4-1.17
		connected_block_textures: Connected Block Textures 0.1.5+1.17
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		craftingpad: Crafting Pad 1.17-fabric0.34.9-1.0.5
		crowdin-translate: CrowdinTranslate 1.3+1.17
		custom-crosshair-mod: Custom Crosshair Mod 1.3.3-fabric
		customfov: Custom FoV 1.4.1-1.17
		damagetilt: Damage Tilt 1.17-fabric-0.1.2
		dark-loading-screen: Dark Loading Screen 1.6.6
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.3
		dynamicfps: Dynamic FPS 2.0.4
		enderitemod: Enderite Mod 1.2.5
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b44633d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b44633d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e3d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b44633d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab61213d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.3+676f40fa3d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b44633d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b44633d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b44633d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa3d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.6
		fallingtree: FallingTree 2.12.1
		fiber: fiber 0.23.0-2
		fpsdisplay: FPS-Display 1.4.1+1.17
		horsestatsvanilla: Horse Stats Vanilla 4.1.8
		iknowwhatimdoing: I Know What I'm Doing 3.0.0
		indium: Indium 1.0.0-dev.d797129+mc1.17.1
		iris: Iris 1.1.2-starline+build.460
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 4.0.0-beta.4+1.17-rc1
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.3
		maelstrom_library: Maelstrom Library 1.2.1-1.17-pre1
		maybe-data: Maybe data 1.0.1-1.17
		minecraft: Minecraft 1.17
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.3-1.17-pre1
		modmenu: Mod Menu 2.0.4
		more-structures-add-on-for-william-wythers-overhauled-overworld: More Structures add-on for William Wythers Overhauled Overworld 1.1
		notenoughcrashes: Not Enough Crashes 3.4.0+1.17
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		org_json_json: json 20210307
		roughlyenoughitems: Roughly Enough Items 6.0.267-alpha
		seamless_loading_screen: Seamless Loading Screen 1.3.5+1.17
		sodium: Sodium 0.3.0+IRIS2-build.114
		somnus: Somnus API 0.0.12-1.17
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		the_loved_ones: The Loved Ones 1.2.0+1.17
		torohealth: ToroHealth Damage Indicators 1.17-fabric-7
		villagerfix: Villager Fix 2.1.3+1.17
		villagernames: Villager Names 2.0.0
		william-wythers-overhauled-overworld: William Wythers Overhauled Overworld 1.5
		wolveswitharmor: Wolves With Armor 1.6.0-1.17
		wthit: wthit 3.8.1
		yungsapi: YUNG's API 1.17-Fabric-15
	Launched Version: fabric-loader-0.11.6-1.17
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.11, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Faithful 1.17.zip, file/Conquest_entities_1.16.zip (incompatible)
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	Player Count: 1 / 8; [class_3222['Dulhan'/4, l='ServerLevel[Cavin]', x=591.62, y=65.00, z=2591.11]]
	Data Packs: vanilla (incompatible), Fabric Mods
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Fabric Loader (fabricloader)
```

**Comment by Rakambda** [comment] 2021-08-10 05:21
Duplicate of #180

**Comment by Rakambda** [comment] 2021-08-10 05:21
Update the mod to latest version

**Closed as not planned** 2021-08-13 09:59 UTC
Labels: type: 🐛 bug, status: duplicate, modloader: Fabric
