### ISSUE TITLE
Incorrect conflict with Cloth

### ISSUE THREAD

**Issue by Zygus42** [RakambdaOrg/FallingTree#103] opened 2021-04-28 08:44 UTC
**Describe the bug**
I was running the latest Forge version of this mod fine, but now I've added another Forge (Origins) mod that's been ported to Forge from Fabric, and it needs the Cloth (Forge) mod.  Your mod is now failing at startup with a message that it needs a different version of Cloth, even though it doesn't actually need Cloth at all.

**Infos:**
 - Minecraft version: 1.16.5
 - Mod version: FallingTree-Forge-1.16.5-2.11.1
 - Forge version:  forge-1.16.5-36.1.12-installer
 - Other Mods: Origins-1.16.5-0.7.0.1-forge
                        cloth-config-4.11.19-forge

If you provide a crash report please include it in a readable way (like pastebin or gist for example).
[crash-2021-04-28_16.36.07-fml.txt](https://github.com/RakSrinaNa/FallingTree/files/6390380/crash-2021-04-28_16.36.07-fml.txt)

**Comment by Rakambda** [comment] 2021-04-28 09:15
Duplicate of #98

**Comment by Rakambda** [comment] 2021-04-28 09:16
Update to latest version

**Closed as not planned by Rakambda** 2021-04-28 09:16 UTC
Labels: status: duplicate, modloader: Forge
