### ISSUE TITLE
Crashreport(2.8.1.)

### ISSUE THREAD

**Issue by Rheinauer** [RakambdaOrg/FallingTree#47] opened 2021-01-03 14:46 UTC
1.16.4-2.8.1 version.  It simply crashed on the loading screen.  Error-Code: Java.lang.IllegalAccessError: no such constructor

crash report:
[crash-2021-01-03_14.44.00-fml.txt](https://github.com/RakSrinaNa/FallingTree/files/5761750/crash-2021-01-03_14.44.00-fml.txt)

**Infos:**
 - Minecraft verson: [1.16.4]
 - Mod loader: [Forge]
 - Mod version: [FallingTree-Forge-1.16.4-2.8.1]

Thank you for your work :D

**Comment by Rakambda** [comment] 2021-01-03 14:51
Duplicate of #38

**Comment by Rakambda** [comment] 2021-01-03 14:51
Install the required dependency

**Closed as completed by Rakambda** 2021-01-03 14:51 UTC
Labels: type: 🐛 bug, modloader: Forge
