### ISSUE TITLE
How about option to include mushroom tree?

### ISSUE THREAD

**Issue by ardissaps** [RakambdaOrg/FallingTree#355] opened 2022-06-05 08:24 UTC
### Describe the feature

thx

**Comment by Rakambda** [comment] 2022-06-05 09:21
Duplicate of #347 

You can have that behavior by adding parts of the mushroom in the config, in particular:
```json
  "allowedLogs": [
    "minecraft:mushroom_stem"
  ],
  "allowedNonDecayLeaves": [
    "minecraft:red_mushroom_block",
    "minecraft:brown_mushroom_block"
  ],
```

**Closed as not planned by Rakambda** 2022-06-05 09:21 UTC
Labels: type: ❔ question, modloader: Forge, modloader: Fabric
