### ISSUE TITLE
Axe gets duplicated

### ISSUE THREAD

**Issue by Flyrija** [RakambdaOrg/FallingTree#25] opened 2020-09-09 16:41 UTC
The mod works like a charm, but every time I cut down a tree or wood, the axe gets duplicated by the number of blocks I cut down and stacks. I have now hundreds of axes in my inventory.

**To Reproduce**
1. Cut down a tree or wood
2. Watch your axe multiply buy the number of blocks you just cut down

**Infos:**
 - Minecraft verson: release fabric loader 0.93 build.207 1.16.1
 - Mod version: FallingTree-Fabric-1.16.1-2.3.1

**Comment by Rakambda** [comment] 2020-09-09 17:53
I can't reproduce it.

* What is the configuration you use? (Can drop the config file here)
* What gamemode are you in when this happens? (I assumed survival)
* Do you have any other mods loaded?

**Comment by Flyrija** [comment] 2020-09-11 17:05
Sorry for the late reply, I was too tired after work. I didn't change anything in the default config except this maybe:

// The minimum amount of leaves that needs to be around the top most log in order for the mod to consider it a tree.
		"minimumLeavesAroundRequired": 0,  <- I think this was set to 3 before?

And I'm using these mods:
                adorn: Adorn 1.10.1+1.16.1
		allure: Allure 1.2.1
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		appleskin: AppleSkin 1.0.11
		artifice: Artifice 0.8.1+1.16.1
		autoconfig1u: Auto Config v1 Updated 3.2.2
		autoswap: Autoswap 1.16-fabric0.13.1-1.0.1
		bambootweaks: Bamboo Tweaks unspecified
		beachslimes: Beach Slimes 2.1.0+mc1.16.1
		beefixed: Bee Fixed 1.0.0
		blockus: Blockus 1.6.2
		blue_endless_jankson: jankson +
		cardinal-components-base: Cardinal Components API (base) 2.4.0-nightly.1.16-rc1.build.2
		cardinal-components-entity: Cardinal Components API (entities) 2.4.0-nightly.1.16-rc1.build.2
		chainmail: Chainmail 0.5.0
		cinderscapes: Cinderscapes 1.0.7+build.43-1.16.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.6.0
		columns: Columns 1.1.0
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compact-storage: CompactStorage 4.0.0
		compressedblocks: Compressed Blocks 1.0
		connected_block_textures: Connected Block Textures 0.1.2+1.16
		couplings: Couplings 1.3.1
		diggusmaximus: Diggus Maximus 1.3.0-1.16
		expandedstorage: ExpandedStorage 5.5.23
		extrapieces: Extra Pieces 2.9.0
		fabric: Fabric API 0.18.0+build.387-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e540c58402
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-furnaces: Fabric Furnaces 1.3.1-1.16.1
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.7+2242e77202
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+be551d3c02
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.1+91fca5cd02
		fabricloader: Fabric Loader 0.9.3+build.207
		falling_tree: FallingTree 2.3.1
		fatxporbs: Fat Experience Orbs 0.0.7
		fiber: fiber 0.23.0-1
		flonters: Flonters 1.1.0+1.16.1
		glassdoor: Glass Doors 1.4.4-1.16
		glassdoors: Glass Doors 0.0.2
		glassential: Glassential 1.16.1-1.1.4
		gravestones: Gravestones 1.4.0
		hollowlogs: Hollow Logs 1.1.0
		horseinfo: Horse Info 0.2.2-1.16.1
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		illuminations: Illuminations 1.0.4
		inventorysorter: Inventory Sorter 1.7.1-1.16
		itemmodelfix: Item Model Fix 0.2.3
		jankson: Jankson 3.0.0+j1.2.0
		kyrptconfig: Kytpt Config 1.1.0-1.16
		lakeside: Lakeside 1.0.2+1.16.1
		lambdynlights: LambDynamicLights 1.2.2+1.16.1
		libcd: LibCapableData 2.5.0+1.16.1
		libgui: LibGui 2.3.0+1.16.1
		libstructure: Libstructure 1.3
		lithium: Lithium 0.5.1
		magna: Magna 1.3.2-1.16.1
		mambience: MAmbience 2.1.0-1.16
		minecraft: Minecraft 1.16.1
		modmenu: Mod Menu 1.14.5+build.30
		morepaths: More Paths 0.0.3
		motiono: motioNO 1.0.1+1.16
		netheritehorsearmor: Netherite Horse Armor 0.4.2-1.16.1
		nomoreglowingpots: No More Glowing Pots 1.0.2
		okzoomer: Ok Zoomer 4.0.0-alpha.5+1.16.1
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		paintingcycle: Painting Cycle 1.0.0
		parchment: Parchment 1.0.2+1.15.2
		phosphor: Phosphor 0.6.0+build.7
		polymorph: Polymorph 0.0.4-1.16.1
		reborncore: Reborn Core 4.3.4+build.64
		repurposed_structures: Repurposed Structures 1.4.6
		ringsofascension: Rings of Ascension 1.0.7
		riverredux: River Redux 0.1.4
		roughlyenoughitems: Roughly Enough Items 4.12.1
		sandwichable: Sandwichable 1.1.1-snapshot
		shapes: Shapes 2.0.0+build.10
		sheepconsistency: Sheep Consistency 1.0.2
		shuffle: Shuffle 1.1.2
		simpleteleporters: Simple Teleporters 2.2.0
		slabhelper: Slab Helper 1.3.2
		smoothbedrock: Smooth Bedrock (Fabric) 1.2.3
		sodium: Sodium 0.1.0
		spruceui: SpruceUI 1.5.8
		stackablepotions: Stackable Potions 1.0.0
		staffofbuilding: Staff of Building 1.2.0-1.16
		static-content: Static Content 1.0.0-1.16.1
		staticdata: Static Data 1.1.2
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.4.5+build.88
		terraform: Terraform 2.3.0+build.33
		terrestria: Terrestria 2.0.6+build.58
		traverse: Traverse 2.2.15+build.30
		trinkets: Trinkets 2.6.3
		vanilla-hammers: Vanilla Hammers 2.0.4-1.16.1
		voxelmap: VoxelMap 1.10.7
		waila: Hwyla 1.9.22
		wands: Wands Mod 1.1
		wolveswitharmor: Wolves With Armor 1.5.1-1.16.1
		woodcutter: Woodcutter 1.2-1.16.1
		xlpackets: XLPackets 1.1

**Comment by Rakambda** [comment] 2020-09-12 09:13
Seems to be a compatibility issue with Allure. Will try to see why but looking at the Allure's curse page it seems to be a rather big mod doing lots of changes so will be kinda hard to find what part could cause that.

--
I sent a private message to the mod author on forge, waiting for a reply.

**Comment by Rakambda** [comment] 2020-09-15 21:02
Got this response from the author:  `Good find! Fixed in the latest release!`.

So I guess you can try with Allure's last release and see if it's fixed.

**Closed as completed** 2020-09-22 06:02 UTC
Labels: type: 🔄 mod compatibility, modloader: Fabric
