### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Matusz27** [RakambdaOrg/FallingTree#102] opened 2021-04-27 15:25 UTC
**Describe the bug**
The game won't start

**To Reproduce**
1.  Install Fallingtrees

**Infos:**
 - Minecraft version: 1.16.5
 - Mod version: 2.11.1
 - Forge version: 36.1.13

![image](https://user-images.githubusercontent.com/52843750/116268399-90fa3780-a77d-11eb-9df9-2104ba0c8403.png)

**Comment by Rakambda** [comment] 2021-04-27 16:05
Already fixed in 2.11.2+

**Comment by Rakambda** [comment] 2021-04-27 16:06
Duplicate of #98

**Closed as not planned by Rakambda** 2021-04-27 16:05 UTC
Labels: type: 🐛 bug, status: duplicate, modloader: Forge
