### ISSUE TITLE
Version 2.8.1 crashes

### ISSUE THREAD

**Issue by Victor-ARC** [RakambdaOrg/FallingTree#42] opened 2020-12-21 23:08 UTC
Hi there,

Today I updated the mod to the 1.16.4-2.8.1 version and it simply crashed Minecraft when loading. I'm attaching the crash report below.

[crash-2020-12-21_16.49.04-fml.txt](https://github.com/RakSrinaNa/FallingTree/files/5726916/crash-2020-12-21_16.49.04-fml.txt)

Contact me if you need any other info.

Best regards and thank you for your work and dedication to the community.

**Comment by Victor-ARC** [comment] 2020-12-22 01:00
UPDATE

Mod version 2.8.0 triggers the following crash report:

[crash-2020-12-21_18.55.17-fml.txt](https://github.com/RakSrinaNa/FallingTree/files/5727188/crash-2020-12-21_18.55.17-fml.txt)

Best regards.

**Comment by Rakambda** [comment] 2020-12-22 06:20
You need to install Cloth Config.
You can find the link on the main page of the mod on curse or on every file on curse it is marked as a required dependency.

![image](https://user-images.githubusercontent.com/1688389/102856121-32ffc100-4426-11eb-8f4c-f4b7283c1645.jpeg)

**Comment by Rakambda** [comment] 2020-12-22 09:11
Duplicate of #38

**Closed as completed** 2020-12-22 23:19 UTC
Labels: reason: 🧍 user issue, modloader: Forge
