### ISSUE TITLE
Mod doesn't respect changed Sneak keybind

### ISSUE THREAD

**Issue by HatTrkPatrk** [RakambdaOrg/FallingTree#426] opened 2022-10-20 00:52 UTC
### Describe the bug

With the functionality to require sneak being held for the mod to do its thing, if you've changed your Sneak keybind the mod doesn't respect it (seems to still require you to hold Shift).

IIRC on 1.16.5 it respected the keybind if you change it.

### Minecraft version

1.19.2

### Forge version

43.1.43

### Mod version

2.11.5

**Comment by Rakambda** [comment] 2022-10-20 05:44
I'll check that later on but it seems rather weird to me. I don't interact with keybinds at all and just check the "sneaking state" of the player.
So regardless of the keying used, when you sneak you sneak 🙃

So you play in single player or on a server?

Can you share the content of your config file?

**Comment by HatTrkPatrk** [comment] 2022-10-20 07:25
I'm on a multiplayer server (one that I host on my LAN).

My config file (for the FallingTree mod): https://pastebin.com/mBhQg8JE

I set it up to require Sneak for the mod to activate. Trees/axes behave as normal (the log you hit is the only one that breaks/is affected) unless sneaking. As for my keybinds, I simply switch LeftCtrl and LeftShift (my personal preference as most other games I play do it that way).

I figure it may help to be able to see it happening, so I also made an OBS recording that demonstrates the issue:
https://www.youtube.com/watch?v=TutBOVE9Qoo

**Comment by Rakambda** [comment] 2022-10-20 07:44
Is the config file the one of the server or of your client?

Only the value of the server will be used.

**Comment by HatTrkPatrk** [comment] 2022-10-20 10:30
Yes, it's the server's.

**Comment by Rakambda** [comment] 2022-10-20 11:58
On the client, do you also have `"sneakMode": "SNEAK_ENABLE",`, or it is the default `SNEAK_DISABLE` ?

**Comment by Rakambda** [comment] 2022-10-20 16:37
What if you try with this version : https://github.com/RakSrinaNa/FallingTree/actions/runs/3291349481
(in the artifacts sections you'll find a zip containing the jar file)

**Comment by Rakambda** [comment] 2022-10-20 17:36
Actually I think it won't fix your issue (just another one). 

I can't reproduce your issue in local. Binding sneak on "h" for example and hitting the tree does work.

https://user-images.githubusercontent.com/1688389/197019108-0ab7b8ba-c529-4ffa-bc95-7883802d5f8b.mp4

Do you manage to reproduce it with just FallingTree ? (like no other mods) It may be an incompatibility with FT and another mod.

**Closed as not planned** 2022-11-22 12:51 UTC
Labels: modloader: Forge
